const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let db,active,reviewQueue=[],reviewIndex=0;
let st=JSON.parse(localStorage.getItem('vq')||'{"name":"","done":[],"seen":[],"scores":{},"last":"","streak":0,"words":{}}');
if(!st.words)st.words={};
const today=()=>new Date().toISOString().slice(0,10), addDays=n=>{let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const key=(setId,word)=>setId+'::'+word;
function defaultWord(){return{seen:0,correct:0,wrong:0,stage:'new',interval:0,due:today(),last:null,ease:2.3,lapses:0,streak:0}}
function wordState(setId,word){let k=key(setId,word);return st.words[k]||(st.words[k]=defaultWord())}
function allWords(){return db.sets.flatMap(s=>s.words.map(w=>({...w,setId:s.id,setTitle:s.title,icon:s.icon,state:wordState(s.id,w.word)})))}
function save(){localStorage.setItem('vq',JSON.stringify(st));stats()}
function startDay(){let t=today(),d=st.last?(new Date(t)-new Date(st.last))/864e5:0;if(!st.last)st.streak=1;else if(d===1)st.streak++;else if(d>1)st.streak=1;st.last=t;save()}
function stats(){if(!db)return;let words=allWords(),n=st.done.length;$('#stats').textContent=`${n} of 20 stages complete • ${words.filter(w=>w.state.seen).length} words practised`;$('.bar i').style.width=n*5+'%';$('#streak').textContent=`🔥 ${st.streak||1} day streak`;$('#name').value=st.name||'';let due=words.filter(w=>w.state.seen&&w.state.due<=today()&&w.state.stage!=='mastered').length,weak=words.filter(w=>isWeak(w.state)).length,mastered=words.filter(w=>w.state.stage==='mastered').length,learning=words.filter(w=>w.state.seen&&w.state.stage!=='mastered').length,newN=words.length-learning-mastered;$('#dueCount').textContent=due;$('#weakCount').textContent=weak;$('#newWords').textContent=newN;$('#learningWords').textContent=learning;$('#dueWords').textContent=due;$('#masteredWords').textContent=mastered;let strength=words.length?Math.round(words.reduce((a,w)=>a+Math.min(w.state.interval,30)/30,0)/words.length*100):0;$('#memoryPct').textContent=strength+'%';$('#memoryFill').style.width=strength+'%'}
function isWeak(x){return x.wrong>=2||(x.seen>=2&&x.correct/Math.max(1,x.seen)<.6)||x.lapses>=1}
function render(){let q=$('#search').value.toLowerCase();$('#grid').innerHTML=db.sets.filter(s=>(s.title+s.arabic+s.words.map(w=>w.word).join()).toLowerCase().includes(q)).map(s=>{let weak=s.words.filter(w=>isWeak(wordState(s.id,w.word))).length;return `<article class="card ${st.done.includes(s.id)?'done':''}"><small>STAGE ${String(s.id).padStart(2,'0')}</small><div class="icon">${s.icon}</div><h3>${s.title}</h3><div class="ar">${s.arabic}</div><p>${weak?`<span class="weakTag">${weak} weak word${weak>1?'s':''}</span>`:'5 high-value words with Arabic support.'}</p><button onclick="openSet(${s.id})">${st.done.includes(s.id)?'✓ Review':'Open stage'}</button></article>`}).join('')}
function record(setId,word,quality){let x=wordState(setId,word);x.seen++;x.last=today();if(quality<2){x.wrong++;x.lapses++;x.streak=0;x.interval=quality===0?0:1;x.ease=Math.max(1.3,x.ease-.2);x.stage='learning';x.due=quality===0?today():addDays(1)}else{x.correct++;x.streak++;if(quality===2){x.interval=x.interval<1?1:Math.max(2,Math.round(x.interval*1.6));}else{x.interval=x.interval<1?3:Math.max(4,Math.round(x.interval*x.ease));x.ease=Math.min(2.8,x.ease+.05)}x.stage=x.interval>=21&&x.correct>=4?'mastered':'learning';x.due=addDays(x.interval)}save();render()}
window.openSet=id=>{active=db.sets.find(s=>s.id===id);if(!st.seen.includes(id))st.seen.push(id);save();$('#inside').innerHTML=`<div class="top"><div><small>STAGE ${id} OF 20</small><h2>${active.icon} ${active.title}</h2></div><button onclick="lesson.close()">✕</button></div><div class="body"><div class="tools"><button onclick="window.print()">🖨 Print list</button><button onclick="csv()">⬇ Save CSV</button><button onclick="startSetReview(${id})">🧠 Review this set</button>${st.done.includes(id)?'<button onclick="certificate()">🏆 Certificate</button>':''}</div><table><thead><tr><th>Word</th><th>Arabic</th><th>Meaning and progress</th></tr></thead><tbody>${active.words.map((w,i)=>{let x=wordState(id,w.word);return `<tr><td><b>${i+1}. ${w.word}</b></td><td class="ar">${w.arabic}</td><td>${w.definition}<small>${w.example}</small><small>${x.stage==='mastered'?'<span class="masterTag">Mastered</span>':x.seen?`Next review: ${x.due} • Interval ${x.interval} day${x.interval===1?'':'s'}`:'New word'}</small></td></tr>`}).join('')}</tbody></table><div class="quiz"><h2>Badge challenge</h2><p>Score 4/5. Every answer also updates the smart review schedule.</p><div id="quizBox"></div><button class="primary" onclick="check()">Check answers</button> <b id="score"></b></div></div>`;build();lesson.showModal()}
function build(){let pool=allWords();$('#quizBox').innerHTML=active.words.map((w,i)=>{let o=[w.word,...pool.filter(x=>x.word!==w.word).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.word)].sort(()=>Math.random()-.5);return `<div class="q" data-a="${w.word}"><b>${i+1}. Which word means “${w.definition}”?</b><div class="opts">${o.map(x=>`<button class="opt" data-v="${x}">${x}</button>`).join('')}</div></div>`}).join('');$$('.opt').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('.opt').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')})}
window.check=()=>{let n=0;$$('.q').forEach(q=>{let p=q.querySelector('.sel'),ok=p?.dataset.v===q.dataset.a;q.querySelectorAll('.opt').forEach(x=>{x.disabled=true;if(x.dataset.v===q.dataset.a)x.classList.add('ok')});if(ok)n++;else p?.classList.add('no');record(active.id,q.dataset.a,ok?2:0)});$('#score').textContent=`Score ${n}/5`;st.scores[active.id]=Math.max(n,st.scores[active.id]||0);if(n>=4){if(!st.done.includes(active.id))st.done.push(active.id);save();render();setTimeout(certificate,350)}else save()}
function launchReview(mode,setId){let words=allWords();if(setId)words=words.filter(w=>w.setId===setId);if(mode==='due')reviewQueue=words.filter(w=>w.state.seen&&w.state.due<=today()&&w.state.stage!=='mastered');if(mode==='weak')reviewQueue=words.filter(w=>isWeak(w.state));if(mode==='set')reviewQueue=words.sort((a,b)=>(isWeak(b.state)-isWeak(a.state))||(a.state.due.localeCompare(b.state.due)));reviewQueue=reviewQueue.sort(()=>Math.random()-.5).slice(0,20);reviewIndex=0;renderReview(mode)}
window.startSetReview=id=>{lesson.close();launchReview('set',id)};
function renderReview(mode){if(!reviewQueue.length){$('#reviewIn').innerHTML=`<div class="top"><h2>Smart Review</h2><button onclick="review.close()">✕</button></div><div class="emptyReview"><div class="big">🌱</div><h2>Nothing is due right now</h2><p>Complete a stage challenge or practise a set to begin building your review schedule.</p><button class="primary" onclick="review.close()">Return to stages</button></div>`;review.showModal();return}showReviewCard()}
function showReviewCard(){if(reviewIndex>=reviewQueue.length){$('#reviewIn').innerHTML=`<div class="top"><h2>Review complete</h2><button onclick="review.close()">✕</button></div><div class="emptyReview"><div class="big">🎉</div><h2>Session completed</h2><p>Your weak-word list and future review dates have been updated.</p><button class="primary" onclick="review.close();stats();render()">Finish</button></div>`;return}let w=reviewQueue[reviewIndex],x=w.state;$('#reviewIn').innerHTML=`<div class="top"><div><small>SMART REVIEW • ${reviewIndex+1} OF ${reviewQueue.length}</small><h2>${w.icon} ${w.setTitle}</h2></div><button onclick="review.close()">✕</button></div><div class="body reviewCard"><div class="reviewMeta"><span>${isWeak(x)?'⚠ Weak-word focus':'Scheduled review'}</span><span>Current interval: ${x.interval} day${x.interval===1?'':'s'}</span></div><div class="prompt"><div><div class="wordBig">${w.word}</div><p class="hint">Recall the meaning before revealing the answer.</p><div id="answer" hidden><div class="arabicBig">${w.arabic}</div><p class="definitionBig">${w.definition}</p><small>${w.example}</small></div></div></div><button id="reveal" class="revealBtn" onclick="revealAnswer()">Reveal answer</button><div id="rating" class="rating"><button onclick="rate(0)">Again<br><small>today</small></button><button onclick="rate(1)">Hard<br><small>1 day</small></button><button onclick="rate(2)">Good<br><small>adaptive</small></button><button onclick="rate(3)">Easy<br><small>longer gap</small></button></div></div>`;review.showModal()}
window.revealAnswer=()=>{$('#answer').hidden=false;$('#reveal').style.display='none';$('#rating').classList.add('show')};window.rate=q=>{let w=reviewQueue[reviewIndex];record(w.setId,w.word,q);reviewIndex++;showReviewCard()};
function dl(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click()}window.csv=()=>{let r=[['Word','Arabic','Definition','Example'],...active.words.map(w=>[w.word,w.arabic,w.definition,w.example])];dl(new Blob(['\ufeff'+r.map(x=>x.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'}),`stage-${active.id}.csv`)};
window.certificate=()=>{let name=(st.name||'Vocabulary Explorer').replace(/[<>]/g,'');$('#certIn').innerHTML=`<div class="certificate"><div><div style="font-size:5rem">🏅</div><small>VOCABULARY QUEST • STAGE ${active.id}</small><h1>Certificate of Achievement</h1><p>This certifies that</p><h2>${name}</h2><p>successfully completed <b>${active.title}</b>.</p><p>${new Date().toLocaleDateString(undefined,{dateStyle:'long'})}</p></div></div><div class="certBtns"><button class="primary" onclick="window.print()">Print / Save as PDF</button> <button onclick="cert.close()">Close</button></div>`;cert.showModal()};
$('#name').oninput=e=>{st.name=e.target.value;save()};$('#search').oninput=render;$('#go').onclick=()=>openSet(db.sets.find(s=>!st.done.includes(s.id))?.id||1);$('#reviewDue').onclick=()=>launchReview('due');$('#weakReview').onclick=()=>launchReview('weak');$('#backup').onclick=()=>dl(new Blob([JSON.stringify({app:'Vocabulary Quest',version:2,state:st},null,2)],{type:'application/json'}),'vocabulary-progress-v2.json');$('#restore').onchange=e=>{let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);st=x.state||x;if(!st.words)st.words={};save();render()}catch{alert('Invalid backup')}};r.readAsText(e.target.files[0])};$('#all').onclick=()=>{$('#inside').innerHTML=`<div class="top"><h2>Complete Vocabulary Lists</h2><button onclick="lesson.close()">✕</button></div><div class="body"><div class="tools"><button onclick="window.print()">🖨 Print / Save PDF</button></div>${db.sets.map(s=>`<h2>${s.icon} ${s.id}. ${s.title}</h2><table><tbody>${s.words.map(w=>`<tr><td><b>${w.word}</b></td><td class="ar">${w.arabic}</td><td>${w.definition}</td></tr>`).join('')}</tbody></table>`).join('')}</div>`;lesson.showModal()};
fetch('data/vocabulary.json').then(r=>r.json()).then(x=>{db=x;startDay();render();stats()}).catch(()=>alert('Publish on GitHub Pages or use a local web server.'));