const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let db,active,reviewQueue=[],reviewIndex=0;
let st=JSON.parse(localStorage.getItem('vq')||'{"name":"","done":[],"seen":[],"scores":{},"last":"","streak":0,"words":{}}');
if(!st.words)st.words={};
const today=()=>new Date().toISOString().slice(0,10), addDays=n=>{let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const key=(setId,word)=>setId+'::'+word;
function defaultWord(){return{seen:0,correct:0,wrong:0,stage:'new',interval:0,due:today(),last:null,ease:2.3,lapses:0,streak:0}}
function wordState(setId,word){let k=key(setId,word);return st.words[k]||(st.words[k]=defaultWord())}
function allWords(){return db.sets.flatMap(s=>s.words.map(w=>({...w,setId:s.id,setTitle:s.title,icon:s.icon,state:wordState(s.id,w.word)})))}
function save(){localStorage.setItem('vq',JSON.stringify(st));stats()}
function startDay(){let t=today(),d=st.last?(new Date(t)-new Date(st.last))/864e5:0;if(!st.last)st.streak=1;else if(d===1)st.streak++;else if(d>1)st.streak=1;st.last=t;save()}
function stats(){if(!db)return;let words=allWords(),n=st.done.length;$('#stats').textContent=`${n} of 20 stages complete • ${words.filter(w=>w.state.seen).length} words practised`;$('.bar i').style.width=`${Math.min(100,Math.round((n/20)*100))}%`;$('.bar i').title=`${n}/20`;}
function isWeak(x){return x.wrong>=2||(x.seen>=2&&x.correct/Math.max(1,x.seen)<.6)||x.lapses>=1}
function render(){let q=$('#search').value.toLowerCase();$('#grid').innerHTML=db.sets.filter(s=>(s.title+s.arabic+s.words.map(w=>w.word).join()).toLowerCase().includes(q)).map(s=>{let weak=s.words.filter(w=>isWeak(wordState(s.id,w.word))).length;return `<div class="card" onclick="openSet(${s.id})"><div class="meta"><span class="icon">${s.icon}</span><div><h3>${s.title}</h3><small>${s.arabic}</small></div></div><div class="tags"><span>${s.words.length} words</span>${weak?`<span class="warn">${weak} weak</span>`:''}</div></div>`}).join('')}
function record(setId,word,quality){let x=wordState(setId,word);x.seen++;x.last=today();if(quality<2){x.wrong++;x.lapses++;x.streak=0;x.interval=quality===0?0:1;x.ease=Math.max(1.3,x.ease-.2);x.stage='new';}else{x.correct++;x.streak++;x.interval=Math.max(1,Math.round((x.interval||1)*x.ease));x.ease=Math.min(3,x.ease+.15);x.stage=x.streak>=3?'review':'learning';}if(quality===0)x.due=today();else if(quality===1)x.due=addDays(1);else if(quality===2)x.due=addDays(3);else if(quality===3)x.due=addDays(7);else x.due=addDays(14);if(!st.done.includes(setId)&&allWords().filter(w=>w.setId===setId&&w.state.seen).length===db.sets.find(s=>s.id===setId).words.length)st.done.push(setId);save();}
window.openSet=id=>{active=db.sets.find(s=>s.id===id);if(!st.seen.includes(id))st.seen.push(id);save();$('#inside').innerHTML=`<div class="top"><div><small>STAGE ${id} OF 20</small><h2>${active.icon} ${active.title}</h2></div><button onclick="lesson.close()">✕</button></div><div class="row"><div class="card big"><p>${active.arabic}</p><p>Ready to review ${active.words.length} words</p></div><div class="card big"><button class="primary" onclick="build();quiz.show()">Start Quiz</button><button onclick="startSetReview(${id})">Smart Review</button></div></div>`;}
function build(){let pool=allWords();$('#quizBox').innerHTML=active.words.map((w,i)=>{let o=[w.word,...pool.filter(x=>x.word!==w.word).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.word)].sort(()=>Math.random()-.5);return `<div class="q" data-a="${w.word}"><div class="qword">${w.word}</div><div class="opts">${o.map(v=>`<button class="opt ${v===w.word?'correct':''}" data-v="${v}" onclick="this.parentNode.querySelector('.sel')?.classList.remove('sel');this.classList.add('sel');">${v}</button>`).join('')}</div></div>`}).join('')}
window.check=()=>{let n=0;$$('.q').forEach(q=>{let p=q.querySelector('.sel'),ok=p?.dataset.v===q.dataset.a;q.querySelectorAll('.opt').forEach(x=>{x.disabled=true;if(x.dataset.v===q.dataset.a)x.classList.add('good');if(p&&x.dataset.v===p.dataset.v&&!ok)x.classList.add('bad');});if(ok)n++;});$('#score').textContent=`${n}/${$$('.q').length}`;}
function launchReview(mode,setId){let words=allWords();if(setId)words=words.filter(w=>w.setId===setId);if(mode==='due')reviewQueue=words.filter(w=>w.state.seen&&w.state.due<=today()&&w.state.stage!=='done');else if(mode==='set')reviewQueue=words.filter(w=>w.state.seen).slice(0,20);else reviewQueue=words.filter(w=>w.state.seen).sort((a,b)=>a.state.due.localeCompare(b.state.due));reviewIndex=0;renderReview(mode);}
window.startSetReview=id=>{lesson.close();launchReview('set',id)};
function renderReview(mode){if(!reviewQueue.length){$('#reviewIn').innerHTML=`<div class="top"><h2>Smart Review</h2><button onclick="review.close()">✕</button></div><div class="emptyReview"><div class="sticker">✨</div><p>No review cards ready.</p></div>`;return;}showReviewCard();}
function showReviewCard(){if(reviewIndex>=reviewQueue.length){$('#reviewIn').innerHTML=`<div class="top"><h2>Review complete</h2><button onclick="review.close()">✕</button></div><div class="emptyReview"><div class="sticker">✅</div><p>You’re all caught up.</p></div>`;return;}let w=reviewQueue[reviewIndex],x=w.state;$('#reviewIn').innerHTML=`<div class="top"><h2>Smart Review</h2><button onclick="review.close()">✕</button></div><div class="card reviewCard"><small>${w.setTitle}</small><h3>${w.word}</h3><p id="answer" hidden>${w.definition||w.meaning||'Definition coming soon.'}</p><div class="reviewActions"><button id="reveal" onclick="revealAnswer()">Reveal</button><div id="rating" class="rating"><button data-rate="0" onclick="rate(0)">Again</button><button data-rate="1" onclick="rate(1)">Hard</button><button data-rate="2" onclick="rate(2)">Good</button><button data-rate="3" onclick="rate(3)">Easy</button></div></div></div>`;}
window.revealAnswer=()=>{$('#answer').hidden=false;$('#reveal').style.display='none';$('#rating').classList.add('show')};window.rate=q=>{let w=reviewQueue[reviewIndex];record(w.setId,w.word,q);reviewIndex++;showReviewCard();}
function dl(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click()}window.csv=()=>{let r=[['Word','Arabic','Definition','Example'],...active.words.map(w=>[w.word,w.arabic,w.definition||'',w.example||''])];dl(new Blob([r.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),'words.csv')}
window.certificate=()=>{let name=(st.name||'Vocabulary Explorer').replace(/[<>]/g,'');$('#certIn').innerHTML=`<div class="certificate"><div><div style="font-size:5rem">🏅</div><small>VOCABULARY CERTIFICATE</small><h2>${name}</h2><p>Completed ${st.done.length} stage(s)</p></div></div>`;}
$('#name').oninput=e=>{st.name=e.target.value;save()};$('#search').oninput=render;$('#go').onclick=()=>openSet(db.sets.find(s=>!st.done.includes(s.id))?.id||1);$('#reviewDue').onclick=()=>launchReview('due');
fetch('vocabulary.json').then(r=>r.json()).then(x=>{db=x;startDay();render();stats()}).catch(()=>alert('Publish on GitHub Pages or use a local web server.'));